name: tcm
dependencies:
  - python
  - pip
  - rtree
  - shapely
  - fiona
  - rasterio>=1.1.0
  - pyproj
  - gdal>=3.0
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - scikit-image
  - pandas
  - pip:
    - utm
    - pigeon-jupyter==0.1.0
    - planetary-computer>=0.3.0rc3
    - pygifsicle
    - imageio